---
- hosts: all

  tasks:
      - name: Unregister a system Red Hat Subscription Management
        shell: subscription-manager unregister 
        ignore_errors: yes

      - name:  Remove all a System Red Hat Subscription Management 
        shell: subscription-manager remove --all
        ignore_errors: yes

      - name: Clean a system Red Hat Subscription Managenement 
        shell: subscription-manager clean 

      - name: Register VM a system Red Hat Portal
        shell: subscription-manager register --username {{ username_rh }} --password {{ password_rh }} 

      - name: Attach VM a system Red Hat Portal
        shell: subscription-manager attach --pool {{ pool_id }} 
